# Generated by Django 5.2.15 on 2026-06-20 15:38

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vault', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WatermarkRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('opacity', models.PositiveSmallIntegerField(default=30, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('rotation', models.SmallIntegerField(default=-30, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('position', models.CharField(choices=[('center', 'Center'), ('diagonal', 'Diagonal'), ('header', 'Header'), ('footer', 'Footer')], default='diagonal', max_length=16)),
                ('include_user_identity', models.BooleanField(default=True)),
                ('include_timestamp', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='watermark_rule', to='vault.vaultdocument')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
